== Projektidee

Ist Zustand
Die Roboter können nicht kontrolliert werden und es gibt keine Anwendung um die Roboter zu Steuern.

Soll Zustand
Man kann die Roboter steuern von einem Gerät aus oder mit einem input Gerät. Außerdem können Einstellungen vorgenommen werden und diese werden gespeichert wenn man angemeldet ist.


== Projektauftrag

=== Projektbezeichnung
Roboter Controller

=== Projekthintergrund
Roboter können nicht gesteuert werden.

=== Projektergebnis
Jeder Roboter hat einen QR Code mit dem man auf eine Internetseite kommt, wo man den Roboter kontrollieren kann. Als zweite Methode könnte man eine Website aufrufen und die ID des Roboters eingeben und ihn steuern. Des weiteren gibt es eine Software die Inputs von Eingabegeräten an einen Server sendet. Man kann auch Einstellungen vornehmen und die Tastenbelegungen ändern und diese Speichern wenn man sich anmeldet.

=== Projektziele
 - Prototyp
 - Kommunikation mit Server
 - übersichtliche Website zum Steuern
 - Speichern der Einstellungen
 - Datenbank aufsetzen
 - Software zum verwalten der Einstellungen

=== Projektbeschreibung
Die Aufgabe der Website ist es dem User zu ermöglichen, den Roboter zu steuern und mit der Software sollte jedes Gerät das der User ansteckt zu einem Input für den Roboter werden.

=== Meilensteine

1. Website Design
2. Entwicklung der Input Geräte Erkennung
3. Kommunikation mit Server
4. Senden und der Empfang von Inputs vom Server
5. Server und Datenbank zum speichern der Nutzerdaten
6. Test und Optimierung

=== Projektressourcen
 - Controller
 - Matte
 - Testhardware

=== Projektrisiken
 - Herausforderungen bei der Entwicklung
 - Kommunikationsprobleme mit dem Server
 - Mangel an Erfahrung in Webseiten designen

=== Projektorganisation
 - Andreas Hasenschwandtner
 - Tobias Richter

==  Projektantrag
=== Projektziele
Das Ziel des Projektes ist eine fertige Website zu haben mit der man die Roboter kontrollieren kann und eine Software die es ermöglicht mit Input Geräten den Roboter zu Steuern. Außerdem wird die Möglichkeit geboten, die Steuerung anzupassen, und diese Einstellungen werden in einer Datenbank gespeichert.

=== Projektumfang:

- Webseite
- Erkennen Von Input Geräten
- Software die Inputs an den Server sendet
- Software um Einstellungen zu verändern
- Kommunikation mit Renn-Server
- Datenbank und Server

=== Projektzeitplan:

1. Website mit QR Codes | 1 - 3. Tag
2. Entwicklung der Input Geräte Erkennung | 3 - 6 Tag
3. Kommunikation mit Server | 6 - 10 Tag
4. Senden der Empfangenen Inputs an den Server | 10 - 15 Tag
5. Implementierung des Servers zum Speichern der Einstellungen der Nutzer | 20 Tage
6. Test und Optimierung | 20 - 22 Tag

=== Ressourcenbedarf:
 - Controller
 - Matte
 - Test Hardware

=== Entwicklungsteam:

- Tobias Richter
- Andreas Hasenschwandtner

=== Finanzielle Ressourcen:
 - 0€

=== Projektabschluss:
Das Projekt wird abgeschlossen, sobald die definierten Ziele erreicht sind und die Softwarelösung erfolgreich getestet und implementiert wurde.
